name: 13 Github context

on:
  workflow_dispatch:
    
jobs:
  print-variables:
    runs-on: ubuntu-22.04
    steps:
      - name: Print variables
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"